Resources:
  CartonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "cartonId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "cartonId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "Cartons"